/* ================================================================
 * cases-chrome.mjs
 *
 * Localized STATIC-TEMPLATE CHROME for the case (playbook) pages.
 *
 * These are the fixed template strings the generator injects that are
 * NOT case content and have no key in the app locales: the <title>
 * descriptor, the steps heading + subtitle, the CTA buttons, the top-nav
 * labels, the "More in <category>" heading, the footer line and its
 * links, and the minute unit. Case content, the flow In/Out labels, the
 * "Why" label, the "N steps" pill, the card "Open" and the nav
 * "Cases"/"Docs" labels are NOT here: they reuse the app locale keys
 * (cases.*, cases.flow.in/out, cases.step.why, cases.card.steps,
 * cases.card.open, nav.cases, nav.docs).
 *
 * Fields:
 *   descriptor    - the <title>/og:title middle segment; the title reads
 *                   "<case> - <descriptor> - OpenConstructionERP".
 *   navTour..navUberization - the top-nav labels with no nav.* key.
 *                   navUberization uses the product's own coined term per
 *                   language (matches the localized whitepaper wording).
 * Placeholders: {n} = step count, {cat} = already-translated category
 * label. House style: plain hyphen only, never an em/en dash; the
 * product name OpenConstructionERP is never translated.
 *
 * English is intentionally absent: English pages render the original
 * template chrome verbatim. A language missing here just keeps English,
 * so keep this in step with the LANGS list in generate-cases.mjs.
 * ================================================================ */

export const CHROME = {
  de: {
    descriptor: 'Bau-Playbook',
    min: 'Min.',
    stepByStep: 'So funktioniert es, Schritt für Schritt',
    sub: '{n} Schritte über die Plattform hinweg - was Sie bei jedem tun und warum es zählt.',
    tryDemo: 'In der Demo ausprobieren',
    openWorkflow: 'Diesen Ablauf in der Demo öffnen',
    browseAll: 'Alle Fallbeispiele ansehen',
    openDemo: 'Demo öffnen',
    moreIn: 'Mehr aus {cat}',
    footerTagline: 'Angeleitete Bau-Playbooks - Teil der OpenConstructionERP-Plattform.',
    footHome: 'Startseite',
    footAllCases: 'Alle Fallbeispiele',
    footLiveDemo: 'Live-Demo',
    navTour: 'Rundgang',
    navCompare: 'Vergleich',
    navPricing: 'Preise',
    navNews: 'Neuigkeiten',
    navUberization: 'Uberisierung',
  },
  fr: {
    descriptor: 'Playbook de construction',
    min: 'min',
    stepByStep: 'Comment ça marche, étape par étape',
    sub: '{n} étapes à travers la plateforme - ce que vous faites à chacune et pourquoi c’est important.',
    tryDemo: 'Essayer dans la démo',
    openWorkflow: 'Ouvrir ce flux dans la démo',
    browseAll: 'Parcourir tous les cas',
    openDemo: 'Ouvrir la démo',
    moreIn: 'Plus dans {cat}',
    footerTagline: 'Playbooks de construction guidés - une partie de la plateforme OpenConstructionERP.',
    footHome: 'Accueil',
    footAllCases: 'Tous les cas',
    footLiveDemo: 'Démo en direct',
    navTour: 'Visite',
    navCompare: 'Comparer',
    navPricing: 'Tarifs',
    navNews: 'Actualités',
    navUberization: 'Uberisation',
  },
  es: {
    descriptor: 'Guía práctica de construcción',
    min: 'min',
    stepByStep: 'Cómo funciona, paso a paso',
    sub: '{n} pasos a lo largo de la plataforma - qué hacer en cada uno y por qué importa.',
    tryDemo: 'Pruébalo en la demo',
    openWorkflow: 'Abrir este flujo en la demo',
    browseAll: 'Ver todos los casos',
    openDemo: 'Abrir la demo',
    moreIn: 'Más en {cat}',
    footerTagline: 'Guías prácticas de construcción - parte de la plataforma OpenConstructionERP.',
    footHome: 'Inicio',
    footAllCases: 'Todos los casos',
    footLiveDemo: 'Demo en vivo',
    navTour: 'Recorrido',
    navCompare: 'Comparar',
    navPricing: 'Precios',
    navNews: 'Novedades',
    navUberization: 'Uberización',
  },
  it: {
    descriptor: 'Playbook di costruzione',
    min: 'min',
    stepByStep: 'Come funziona, passo dopo passo',
    sub: '{n} passi attraverso la piattaforma - cosa fare a ciascuno e perché conta.',
    tryDemo: 'Provalo nella demo',
    openWorkflow: 'Apri questo flusso nella demo',
    browseAll: 'Sfoglia tutti i casi',
    openDemo: 'Apri la demo',
    moreIn: 'Altro in {cat}',
    footerTagline: 'Playbook di costruzione guidati - parte della piattaforma OpenConstructionERP.',
    footHome: 'Home',
    footAllCases: 'Tutti i casi',
    footLiveDemo: 'Demo dal vivo',
    navTour: 'Tour',
    navCompare: 'Confronto',
    navPricing: 'Prezzi',
    navNews: 'Novità',
    navUberization: 'Uberizzazione',
  },
  pt: {
    descriptor: 'Guia prático de construção',
    min: 'min',
    stepByStep: 'Como funciona, passo a passo',
    sub: '{n} passos ao longo da plataforma - o que fazer em cada um e por que importa.',
    tryDemo: 'Experimente na demo',
    openWorkflow: 'Abrir este fluxo na demo',
    browseAll: 'Ver todos os casos',
    openDemo: 'Abrir a demo',
    moreIn: 'Mais em {cat}',
    footerTagline: 'Guias práticos de construção - parte da plataforma OpenConstructionERP.',
    footHome: 'Início',
    footAllCases: 'Todos os casos',
    footLiveDemo: 'Demo ao vivo',
    navTour: 'Tour',
    navCompare: 'Comparar',
    navPricing: 'Preços',
    navNews: 'Notícias',
    navUberization: 'Uberização',
  },
  nl: {
    descriptor: 'Bouw-playbook',
    min: 'min',
    stepByStep: 'Zo werkt het, stap voor stap',
    sub: '{n} stappen door het platform - wat je bij elke stap doet en waarom het ertoe doet.',
    tryDemo: 'Probeer het in de demo',
    openWorkflow: 'Open deze workflow in de demo',
    browseAll: 'Alle cases bekijken',
    openDemo: 'Demo openen',
    moreIn: 'Meer in {cat}',
    footerTagline: 'Begeleide bouw-playbooks - onderdeel van het OpenConstructionERP-platform.',
    footHome: 'Home',
    footAllCases: 'Alle cases',
    footLiveDemo: 'Live demo',
    navTour: 'Rondleiding',
    navCompare: 'Vergelijken',
    navPricing: 'Prijzen',
    navNews: 'Nieuws',
    navUberization: 'Uberisering',
  },
  pl: {
    descriptor: 'Poradnik budowlany',
    min: 'min',
    stepByStep: 'Jak to działa, krok po kroku',
    sub: '{n} kroków w całej platformie - co robisz na każdym z nich i dlaczego to ważne.',
    tryDemo: 'Wypróbuj w wersji demo',
    openWorkflow: 'Otwórz ten przepływ w wersji demo',
    browseAll: 'Przeglądaj wszystkie przypadki',
    openDemo: 'Otwórz demo',
    moreIn: 'Więcej w kategorii {cat}',
    footerTagline: 'Prowadzone poradniki budowlane - część platformy OpenConstructionERP.',
    footHome: 'Strona główna',
    footAllCases: 'Wszystkie przypadki',
    footLiveDemo: 'Demo na żywo',
    navTour: 'Prezentacja',
    navCompare: 'Porównanie',
    navPricing: 'Cennik',
    navNews: 'Aktualności',
    navUberization: 'Uberyzacja',
  },
  cs: {
    descriptor: 'Stavební playbook',
    min: 'min',
    stepByStep: 'Jak to funguje, krok za krokem',
    sub: '{n} kroků napříč platformou - co na každém uděláte a proč na tom záleží.',
    tryDemo: 'Vyzkoušet v demu',
    openWorkflow: 'Otevřít tento postup v demu',
    browseAll: 'Procházet všechny případy',
    openDemo: 'Otevřít demo',
    moreIn: 'Více v kategorii {cat}',
    footerTagline: 'Vedené stavební playbooky - součást platformy OpenConstructionERP.',
    footHome: 'Domů',
    footAllCases: 'Všechny případy',
    footLiveDemo: 'Živé demo',
    navTour: 'Prohlídka',
    navCompare: 'Porovnání',
    navPricing: 'Ceník',
    navNews: 'Novinky',
    navUberization: 'Uberizace',
  },
  ru: {
    descriptor: 'Строительный сценарий',
    min: 'мин',
    stepByStep: 'Как это работает, шаг за шагом',
    sub: '{n} шагов через всю платформу - что делать на каждом и почему это важно.',
    tryDemo: 'Попробовать в демо',
    openWorkflow: 'Открыть этот процесс в демо',
    browseAll: 'Все кейсы',
    openDemo: 'Открыть демо',
    moreIn: 'Ещё в разделе {cat}',
    footerTagline: 'Пошаговые строительные сценарии - часть платформы OpenConstructionERP.',
    footHome: 'Главная',
    footAllCases: 'Все кейсы',
    footLiveDemo: 'Живое демо',
    navTour: 'Обзор',
    navCompare: 'Сравнение',
    navPricing: 'Цены',
    navNews: 'Новости',
    navUberization: 'Уберизация',
  },
  bg: {
    descriptor: 'Строителен сценарий',
    min: 'мин',
    stepByStep: 'Как работи, стъпка по стъпка',
    sub: '{n} стъпки през платформата - какво правите на всяка и защо е важно.',
    tryDemo: 'Изпробвайте в демото',
    openWorkflow: 'Отворете този процес в демото',
    browseAll: 'Всички казуси',
    openDemo: 'Отворете демото',
    moreIn: 'Още в {cat}',
    footerTagline: 'Ръководени строителни сценарии - част от платформата OpenConstructionERP.',
    footHome: 'Начало',
    footAllCases: 'Всички казуси',
    footLiveDemo: 'Демо на живо',
    navTour: 'Обиколка',
    navCompare: 'Сравнение',
    navPricing: 'Цени',
    navNews: 'Новини',
    navUberization: 'Уберизация',
  },
  tr: {
    descriptor: 'İnşaat senaryosu',
    min: 'dk',
    stepByStep: 'Nasıl çalışır, adım adım',
    sub: 'Platform genelinde {n} adım - her birinde ne yapacağınız ve neden önemli olduğu.',
    tryDemo: 'Demoda deneyin',
    openWorkflow: 'Bu iş akışını demoda açın',
    browseAll: 'Tüm vakalara göz atın',
    openDemo: 'Demoyu aç',
    moreIn: '{cat} kategorisinde daha fazlası',
    footerTagline: 'Rehberli inşaat senaryoları - OpenConstructionERP platformunun bir parçası.',
    footHome: 'Ana sayfa',
    footAllCases: 'Tüm vakalar',
    footLiveDemo: 'Canlı demo',
    navTour: 'Tanıtım',
    navCompare: 'Karşılaştır',
    navPricing: 'Fiyatlar',
    navNews: 'Haberler',
    navUberization: 'Uberleşme',
  },
  sv: {
    descriptor: 'Byggplaybook',
    min: 'min',
    stepByStep: 'Så fungerar det, steg för steg',
    sub: '{n} steg genom plattformen - vad du gör i varje och varför det spelar roll.',
    tryDemo: 'Prova i demon',
    openWorkflow: 'Öppna det här flödet i demon',
    browseAll: 'Bläddra bland alla case',
    openDemo: 'Öppna demo',
    moreIn: 'Mer inom {cat}',
    footerTagline: 'Guidade byggplaybooks - en del av plattformen OpenConstructionERP.',
    footHome: 'Hem',
    footAllCases: 'Alla case',
    footLiveDemo: 'Livedemo',
    navTour: 'Rundtur',
    navCompare: 'Jämför',
    navPricing: 'Priser',
    navNews: 'Nyheter',
    navUberization: 'Uberisering',
  },
  no: {
    descriptor: 'Bygg-playbook',
    min: 'min',
    stepByStep: 'Slik fungerer det, steg for steg',
    sub: '{n} trinn gjennom plattformen - hva du gjør i hvert og hvorfor det betyr noe.',
    tryDemo: 'Prøv i demoen',
    openWorkflow: 'Åpne denne arbeidsflyten i demoen',
    browseAll: 'Bla gjennom alle case',
    openDemo: 'Åpne demo',
    moreIn: 'Mer innen {cat}',
    footerTagline: 'Veiledede bygg-playbooks - en del av OpenConstructionERP-plattformen.',
    footHome: 'Hjem',
    footAllCases: 'Alle case',
    footLiveDemo: 'Live-demo',
    navTour: 'Omvisning',
    navCompare: 'Sammenlign',
    navPricing: 'Priser',
    navNews: 'Nyheter',
    navUberization: 'Uberisering',
  },
  fi: {
    descriptor: 'Rakennusopas',
    min: 'min',
    stepByStep: 'Näin se toimii, vaihe vaiheelta',
    sub: '{n} vaihetta läpi alustan - mitä teet kussakin ja miksi sillä on merkitystä.',
    tryDemo: 'Kokeile demossa',
    openWorkflow: 'Avaa tämä työnkulku demossa',
    browseAll: 'Selaa kaikkia tapauksia',
    openDemo: 'Avaa demo',
    moreIn: 'Lisää aiheesta {cat}',
    footerTagline: 'Ohjatut rakennusoppaat - osa OpenConstructionERP-alustaa.',
    footHome: 'Etusivu',
    footAllCases: 'Kaikki tapaukset',
    footLiveDemo: 'Live-demo',
    navTour: 'Kierros',
    navCompare: 'Vertaa',
    navPricing: 'Hinnat',
    navNews: 'Uutiset',
    navUberization: 'Uberisaatio',
  },
  da: {
    descriptor: 'Bygge-playbook',
    min: 'min',
    stepByStep: 'Sådan fungerer det, trin for trin',
    sub: '{n} trin gennem platformen - hvad du gør i hvert, og hvorfor det betyder noget.',
    tryDemo: 'Prøv det i demoen',
    openWorkflow: 'Åbn dette workflow i demoen',
    browseAll: 'Gennemse alle cases',
    openDemo: 'Åbn demo',
    moreIn: 'Mere inden for {cat}',
    footerTagline: 'Guidede bygge-playbooks - en del af OpenConstructionERP-platformen.',
    footHome: 'Hjem',
    footAllCases: 'Alle cases',
    footLiveDemo: 'Live-demo',
    navTour: 'Rundvisning',
    navCompare: 'Sammenlign',
    navPricing: 'Priser',
    navNews: 'Nyheder',
    navUberization: 'Uberisering',
  },
  ar: {
    descriptor: 'دليل بناء إرشادي',
    min: 'دقيقة',
    stepByStep: 'كيف يعمل، خطوة بخطوة',
    sub: '{n} خطوات عبر المنصة - ما تفعله في كل منها ولماذا يهم.',
    tryDemo: 'جرّبه في العرض التجريبي',
    openWorkflow: 'افتح سير العمل هذا في العرض التجريبي',
    browseAll: 'تصفّح كل الحالات',
    openDemo: 'افتح العرض التجريبي',
    moreIn: 'المزيد في {cat}',
    footerTagline: 'أدلة إرشادية للبناء - جزء من منصة OpenConstructionERP.',
    footHome: 'الرئيسية',
    footAllCases: 'كل الحالات',
    footLiveDemo: 'عرض حي',
    navTour: 'جولة',
    navCompare: 'قارن',
    navPricing: 'الأسعار',
    navNews: 'الأخبار',
    navUberization: 'أبرزة',
  },
  zh: {
    descriptor: '施工操作手册',
    min: '分钟',
    stepByStep: '运作方式，逐步说明',
    sub: '贯穿平台的 {n} 个步骤 - 每一步做什么，以及为什么重要。',
    tryDemo: '在演示中试用',
    openWorkflow: '在演示中打开此工作流',
    browseAll: '浏览所有案例',
    openDemo: '打开演示',
    moreIn: '更多 {cat} 案例',
    footerTagline: '分步施工操作手册 - OpenConstructionERP 平台的一部分。',
    footHome: '首页',
    footAllCases: '所有案例',
    footLiveDemo: '在线演示',
    navTour: '导览',
    navCompare: '对比',
    navPricing: '定价',
    navNews: '新闻',
    navUberization: '优步化',
  },
  ja: {
    descriptor: '建設プレイブック',
    min: '分',
    stepByStep: '仕組みをステップごとに',
    sub: 'プラットフォーム全体で{n}ステップ - 各ステップで何をするか、そしてなぜ重要か。',
    tryDemo: 'デモで試す',
    openWorkflow: 'このワークフローをデモで開く',
    browseAll: 'すべてのケースを見る',
    openDemo: 'デモを開く',
    moreIn: '{cat}の他のケース',
    footerTagline: 'ガイド付き建設プレイブック - OpenConstructionERP プラットフォームの一部です。',
    footHome: 'ホーム',
    footAllCases: 'すべてのケース',
    footLiveDemo: 'ライブデモ',
    navTour: 'ツアー',
    navCompare: '比較',
    navPricing: '料金',
    navNews: 'ニュース',
    navUberization: 'ウーバー化',
  },
  ko: {
    descriptor: '건설 플레이북',
    min: '분',
    stepByStep: '작동 방식, 단계별로',
    sub: '플랫폼 전반에 걸친 {n}단계 - 각 단계에서 무엇을 하는지, 그리고 왜 중요한지.',
    tryDemo: '데모에서 사용해 보기',
    openWorkflow: '이 워크플로를 데모에서 열기',
    browseAll: '모든 케이스 보기',
    openDemo: '데모 열기',
    moreIn: '{cat} 카테고리의 더 보기',
    footerTagline: '가이드형 건설 플레이북 - OpenConstructionERP 플랫폼의 일부입니다.',
    footHome: '홈',
    footAllCases: '모든 케이스',
    footLiveDemo: '라이브 데모',
    navTour: '둘러보기',
    navCompare: '비교',
    navPricing: '요금제',
    navNews: '뉴스',
    navUberization: '우버화',
  },
  hi: {
    descriptor: 'निर्माण प्लेबुक',
    min: 'मिनट',
    stepByStep: 'यह कैसे काम करता है, चरण दर चरण',
    sub: 'प्लेटफ़ॉर्म भर में {n} चरण - हर एक में आप क्या करते हैं और यह क्यों मायने रखता है।',
    tryDemo: 'डेमो में आज़माएँ',
    openWorkflow: 'इस वर्कफ़्लो को डेमो में खोलें',
    browseAll: 'सभी केस देखें',
    openDemo: 'डेमो खोलें',
    moreIn: '{cat} में और देखें',
    footerTagline: 'मार्गदर्शित निर्माण प्लेबुक - OpenConstructionERP प्लेटफ़ॉर्म का हिस्सा।',
    footHome: 'होम',
    footAllCases: 'सभी केस',
    footLiveDemo: 'लाइव डेमो',
    navTour: 'टूर',
    navCompare: 'तुलना',
    navPricing: 'मूल्य',
    navNews: 'समाचार',
    navUberization: 'उबरीकरण',
  },
  hr: {
    descriptor: 'Građevinski priručnik',
    min: 'min',
    stepByStep: 'Kako funkcionira, korak po korak',
    sub: '{n} koraka kroz platformu - što radite u svakom i zašto je važno.',
    tryDemo: 'Isprobajte u demu',
    openWorkflow: 'Otvorite ovaj tijek rada u demu',
    browseAll: 'Pregledaj sve slučajeve',
    openDemo: 'Otvori demo',
    moreIn: 'Više u kategoriji {cat}',
    footerTagline: 'Vođeni građevinski priručnici - dio platforme OpenConstructionERP.',
    footHome: 'Početna',
    footAllCases: 'Svi slučajevi',
    footLiveDemo: 'Demo uživo',
    navTour: 'Obilazak',
    navCompare: 'Usporedba',
    navPricing: 'Cijene',
    navNews: 'Novosti',
    navUberization: 'Uberizacija',
  },
  id: {
    descriptor: 'Playbook konstruksi',
    min: 'mnt',
    stepByStep: 'Cara kerjanya, langkah demi langkah',
    sub: '{n} langkah di seluruh platform - apa yang Anda lakukan di setiap langkah dan mengapa itu penting.',
    tryDemo: 'Coba di demo',
    openWorkflow: 'Buka alur kerja ini di demo',
    browseAll: 'Jelajahi semua kasus',
    openDemo: 'Buka demo',
    moreIn: 'Lainnya di {cat}',
    footerTagline: 'Playbook konstruksi terpandu - bagian dari platform OpenConstructionERP.',
    footHome: 'Beranda',
    footAllCases: 'Semua kasus',
    footLiveDemo: 'Demo langsung',
    navTour: 'Tur',
    navCompare: 'Bandingkan',
    navPricing: 'Harga',
    navNews: 'Berita',
    navUberization: 'Uberisasi',
  },
  mn: {
    descriptor: 'Барилгын плейбүүк',
    min: 'мин',
    stepByStep: 'Хэрхэн ажилладаг, алхам алхмаар',
    sub: 'Платформ даяар {n} алхам - алхам бүрт юу хийх, яагаад чухал болохыг.',
    tryDemo: 'Демо дээр туршиж үзэх',
    openWorkflow: 'Энэ ажлын урсгалыг демо дээр нээх',
    browseAll: 'Бүх кейсийг үзэх',
    openDemo: 'Демо нээх',
    moreIn: '{cat} дахь бусад',
    footerTagline: 'Заавартай барилгын плейбүүк - OpenConstructionERP платформын нэг хэсэг.',
    footHome: 'Нүүр',
    footAllCases: 'Бүх кейс',
    footLiveDemo: 'Шууд демо',
    navTour: 'Танилцуулга',
    navCompare: 'Харьцуулах',
    navPricing: 'Үнэ',
    navNews: 'Мэдээ',
    navUberization: 'Убержилт',
  },
  ro: {
    descriptor: 'Ghid practic de construcții',
    min: 'min',
    stepByStep: 'Cum funcționează, pas cu pas',
    sub: '{n} pași în cadrul platformei - ce faceți la fiecare și de ce contează.',
    tryDemo: 'Încercați în demo',
    openWorkflow: 'Deschideți acest flux în demo',
    browseAll: 'Vedeți toate cazurile',
    openDemo: 'Deschideți demo',
    moreIn: 'Mai multe în {cat}',
    footerTagline: 'Ghiduri practice de construcții - parte a platformei OpenConstructionERP.',
    footHome: 'Acasă',
    footAllCases: 'Toate cazurile',
    footLiveDemo: 'Demo live',
    navTour: 'Tur',
    navCompare: 'Comparație',
    navPricing: 'Prețuri',
    navNews: 'Noutăți',
    navUberization: 'Uberizare',
  },
  th: {
    descriptor: 'คู่มือก่อสร้าง',
    min: 'นาที',
    stepByStep: 'วิธีการทำงาน ทีละขั้นตอน',
    sub: '{n} ขั้นตอนทั่วทั้งแพลตฟอร์ม - สิ่งที่คุณทำในแต่ละขั้นและเหตุผลที่สำคัญ',
    tryDemo: 'ลองใช้ในเดโม',
    openWorkflow: 'เปิดเวิร์กโฟลว์นี้ในเดโม',
    browseAll: 'ดูเคสทั้งหมด',
    openDemo: 'เปิดเดโม',
    moreIn: 'เพิ่มเติมใน {cat}',
    footerTagline: 'คู่มือก่อสร้างแบบมีคำแนะนำ - ส่วนหนึ่งของแพลตฟอร์ม OpenConstructionERP',
    footHome: 'หน้าแรก',
    footAllCases: 'เคสทั้งหมด',
    footLiveDemo: 'เดโมสด',
    navTour: 'ทัวร์',
    navCompare: 'เปรียบเทียบ',
    navPricing: 'ราคา',
    navNews: 'ข่าว',
    navUberization: 'Uberization',
  },
  vi: {
    descriptor: 'Cẩm nang xây dựng',
    min: 'phút',
    stepByStep: 'Cách hoạt động, từng bước một',
    sub: '{n} bước xuyên suốt nền tảng - bạn làm gì ở mỗi bước và vì sao điều đó quan trọng.',
    tryDemo: 'Dùng thử trong bản demo',
    openWorkflow: 'Mở quy trình này trong bản demo',
    browseAll: 'Xem tất cả các tình huống',
    openDemo: 'Mở bản demo',
    moreIn: 'Thêm trong {cat}',
    footerTagline: 'Cẩm nang xây dựng có hướng dẫn - một phần của nền tảng OpenConstructionERP.',
    footHome: 'Trang chủ',
    footAllCases: 'Tất cả tình huống',
    footLiveDemo: 'Demo trực tiếp',
    navTour: 'Tham quan',
    navCompare: 'So sánh',
    navPricing: 'Bảng giá',
    navNews: 'Tin tức',
    navUberization: 'Uber hóa',
  },
  'es-mx': {
    descriptor: 'Guía práctica de construcción',
    min: 'min',
    stepByStep: 'Cómo funciona, paso a paso',
    sub: '{n} pasos a lo largo de la plataforma - qué haces en cada uno y por qué importa.',
    tryDemo: 'Pruébalo en la demo',
    openWorkflow: 'Abrir este flujo en la demo',
    browseAll: 'Ver todos los casos',
    openDemo: 'Abrir la demo',
    moreIn: 'Más en {cat}',
    footerTagline: 'Guías prácticas de construcción - parte de la plataforma OpenConstructionERP.',
    footHome: 'Inicio',
    footAllCases: 'Todos los casos',
    footLiveDemo: 'Demo en vivo',
    navTour: 'Recorrido',
    navCompare: 'Comparar',
    navPricing: 'Precios',
    navNews: 'Novedades',
    navUberization: 'Uberización',
  },
};

/* ================================================================
 * NAV_PILL - the two right-hand nav pill labels (Demo, Download) that
 * the homepage header carries. The GitHub pill keeps its brand name in
 * every language, so it is not listed here. English pages fall back to
 * the literals 'Demo' / 'Download'. Kept in step with the LANGS list.
 * ================================================================ */
export const NAV_PILL = {
  de: { demo: 'Demo', download: 'Herunterladen' },
  fr: { demo: 'Démo', download: 'Télécharger' },
  es: { demo: 'Demo', download: 'Descargar' },
  it: { demo: 'Demo', download: 'Scarica' },
  pt: { demo: 'Demo', download: 'Baixar' },
  nl: { demo: 'Demo', download: 'Downloaden' },
  pl: { demo: 'Demo', download: 'Pobierz' },
  cs: { demo: 'Demo', download: 'Stáhnout' },
  ru: { demo: 'Демо', download: 'Скачать' },
  bg: { demo: 'Демо', download: 'Изтегляне' },
  tr: { demo: 'Demo', download: 'İndir' },
  sv: { demo: 'Demo', download: 'Ladda ner' },
  no: { demo: 'Demo', download: 'Last ned' },
  fi: { demo: 'Demo', download: 'Lataa' },
  da: { demo: 'Demo', download: 'Download' },
  ar: { demo: 'عرض تجريبي', download: 'تنزيل' },
  zh: { demo: '演示', download: '下载' },
  ja: { demo: 'デモ', download: 'ダウンロード' },
  ko: { demo: '데모', download: '다운로드' },
  hi: { demo: 'डेमो', download: 'डाउनलोड' },
  hr: { demo: 'Demo', download: 'Preuzmi' },
  id: { demo: 'Demo', download: 'Unduh' },
  mn: { demo: 'Демо', download: 'Татах' },
  ro: { demo: 'Demo', download: 'Descarcă' },
  th: { demo: 'เดโม', download: 'ดาวน์โหลด' },
  vi: { demo: 'Demo', download: 'Tải xuống' },
  'es-mx': { demo: 'Demo', download: 'Descargar' },
};
